### ISSUE TITLE
numpy.hpp#linspace() may lead to division by zero for number = 1

### ISSUE THREAD

**Issue by kartben** [edgeimpulse/inferencing-sdk-cpp#1]
```
    static int linspace(float start, float stop, uint32_t number, float *out)
    {
        if (number < 1 || !out) {
            EIDSP_ERR(EIDSP_PARAMETER_INVALID);
        }

        // step size
        float step = (stop - start) / (number - 1);
```

first check should probably by "if (number <= 1 ... ", or there should be a special case for n=1

**Comment by janjongboom** [comment]
@kartben Thanks, that was actually the case already, but I see that I changed this in https://github.com/edgeimpulse/inferencing-sdk-cpp/commit/85398bb42dbef753bcabe1227bab97f3327a91a9... But apparently not correct!

**Comment by janjongboom** [comment]
Fixed in https://github.com/edgeimpulse/inferencing-sdk-cpp/commit/a3901c8a30d073e13276049df6ecbda36fdcf4b8.
