### ISSUE TITLE
spectral_power_edges  results 

### ISSUE THREAD

**Issue by labviewegypt** [edgeimpulse/inferencing-sdk-cpp#2]
Hi Jan
I am trying to implement all features api in C for my stm32 MCU.
I succeeded for all api (getting the same features results from my C api comparing to the features from my edgeimpulse account from the same input sample ).
But, I am facing issues in the results of 
"spectral_power_edges" api. I tried to use the same steps you are using within the api but unfortunately, I not understand your steps in these 2 api ( periodogram and spectral_power_edges). 
I checked the internet for reference example or api for the periods pectoral periodogram(Welch's method) but most of them not helpful or difficult to implement in C.
So, Could you please send the main  equations which you used to implement both periodogram and spectral_power_edges.

**Comment by janjongboom** [comment]
Handled over email.
