### ISSUE TITLE
Add extern "C" to ei_classifier_porting.h functions

### ISSUE THREAD

**Issue by kartben** [edgeimpulse/inferencing-sdk-cpp#3]
Currently, taking the C inferencing sample as an example, it doesn't actually link to the ei_printf, ei_sleep etc. functions defined in e.g the POSIX porting layer since it's compiled with C++ linkage info (note that it uses printf() to log traces, not ei_printf() :-)). 

Happy to provide a patch if you think this makes sense to add extern C declarations to help with C client apps.

**Comment by kartben** [comment]
BTW I think there is also an opportunity to change the way TF Lite Micro's debug_log.h is included in this file -- it has an "unguarded" extern C declaration of DebugLog(), so it can cause issues when client app is C.

**Comment by kartben** [comment]
Here's what I did for now (note that I removed the debug_log include altogether, which probably ain't right... Should debug_log.h be fixed upstream?)

```diff
*** classifier/ei_run_dsp.h	Thu Jul  2 19:16:40 2020
--- classifier/ei_run_dsp.h	Thu Jul  2 16:59:17 2020
***************
*** 27,39 ****
  #include "edge-impulse-sdk/dsp/spectral/spectral.hpp"
  #include "edge-impulse-sdk/dsp/speechpy/speechpy.hpp"
  
- #ifdef __cplusplus
-  extern "C" {
- #endif
  extern void ei_printf(const char *format, ...);
- #ifdef __cplusplus
-  }
- #endif
  
  #ifdef __cplusplus
  namespace {
--- 27,33 ----
*** porting/ei_classifier_porting.h	Thu Jul  2 19:15:16 2020
--- porting/ei_classifier_porting.h	Thu Jul  2 16:59:18 2020
***************
*** 24,33 ****
  #define _EI_CLASSIFIER_PORTING_H_
  
  #include <stdint.h>
! 
! #ifdef __cplusplus
!  extern "C" {
! #endif
  
  typedef enum {
      EI_IMPULSE_OK = 0,
--- 24,30 ----
  #define _EI_CLASSIFIER_PORTING_H_
  
  #include <stdint.h>
! #include "tensorflow/lite/micro/debug_log.h"
  
  typedef enum {
      EI_IMPULSE_OK = 0,
***************
*** 71,79 ****
   * If not overriden, this will be sent through `ei_printf()`.
   */
  void ei_printf_float(float f);
- 
- #ifdef __cplusplus
-  }
- #endif
  
  #endif // _EI_CLASSIFIER_PORTING_H_
--- 68,72 ----
```

**Comment by janjongboom** [comment]
@kartben Thanks a lot for all of these, I've fixed these upstream and new release will be out on Monday (will sync back to this repo then).

**Comment by kartben** [comment]
Awesome! Thank you.

**Comment by janjongboom** [comment]
@kartben Took a bit longer than anticipated, but this is now done and will be released later today. You will need to set the `EI_C_LINKAGE=1` macro when building. Have updated https://github.com/edgeimpulse/example-standalone-inferencing-c to reflect this and this will build out-of-the-box again for new exports!
