### ISSUE TITLE
esp_nn.h missing (at least for Arduino library builds)

### ISSUE THREAD

**Issue by ShawnHymel** [edgeimpulse/inferencing-sdk-cpp#8]
Reported from a user: [https://forum.edgeimpulse.com/t/i-am-gettting-error-whiile-compiling-arduino-code/5382](https://forum.edgeimpulse.com/t/i-am-gettting-error-whiile-compiling-arduino-code/5382)

Looks like somewhere, esp_nn.h does not get included in the build (at least for Arduino). 

![image](https://user-images.githubusercontent.com/5232145/189933966-c36fe55a-ba43-46c3-82c3-ec59369b4f9a.png)

**Comment by ShawnHymel** [comment]
Tagging @AIWintermuteAI, as this looks like an ESP32 thing.

**Comment by AIWintermuteAI** [comment]
Yes and it only affects ESP32 Arduino builds, which we do not support at the moment :)
I'm investigating a possible workaround for users to disable ESP NN for Arduino until we add the support.

**Comment by vil-nakul** [comment]
Is there a workaround for esp32 boards.

**Comment by AIWintermuteAI** [comment]
Yes, look at the forum post.

**Comment by vil-nakul** [comment]
Ok Thanks. But does turning off ESP NN affect the inference time?

**Comment by AIWintermuteAI** [comment]
It was not on before for Arduino builds. So if you were using Arduino IDE for ESP32 you will not see any difference. To use ESP NN, you need to build with ESP IDF. That is until I merge the PR, which will take 1-2 weeks.

**Comment by automatiek** [comment]
PR #5025

**Comment by AIWintermuteAI** [comment]
PR #5025 should have fixed this. If issue persists, feel free to reopen.

**Comment by vegeta340** [comment]
Issue still exist in builds done today. Fingers crossed for a solution!

**Comment by AIWintermuteAI** [comment]
Hmm, yes, it was not deployed to production yet. I'll reopen and close this when it is.

**Comment by AIWintermuteAI** [comment]
It's in production now, I downloaded new deployment and successfully flashed ESP-EYE with an example.
By the way, we also added Arduino sketches for fusion, microphone and camera sensor inference in this release!
![image](https://user-images.githubusercontent.com/32562299/197206108-98275c21-70b7-4792-9c4f-079a107ab383.png)
